# Generated by Django 4.0 on 2022-01-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccounts',
            name='status',
            field=models.CharField(choices=[('v', 'Verified'), ('un', 'UnVerified')], default='v', max_length=10),
        ),
    ]
