# Generated by Django 4.0 on 2022-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=50)),
                ('yesterday_total', models.IntegerField(default=0)),
                ('today_total', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('yesterday_icospeaks', models.IntegerField(default=0)),
                ('today_icospeaks', models.IntegerField(default=0)),
                ('yesterday_cryptocom', models.IntegerField(default=0)),
                ('today_cryptocom', models.IntegerField(default=0)),
                ('yesterday_coinmarket', models.IntegerField(default=0)),
                ('today_coinmarket', models.IntegerField(default=0)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
