# Generated by Django 4.0 on 2022-01-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='difference',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='today_coinmarket',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='today_cryptocom',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='today_icospeaks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='today_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='yesterday_coinmarket',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='yesterday_cryptocom',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='yesterday_icospeaks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='yesterday_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
