# Generated by Django 4.0 on 2022-01-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchdata', '0002_alter_data_difference_alter_data_today_coinmarket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(max_length=255)),
                ('cryptocurrency', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=50)),
                ('yesterday_total', models.IntegerField(default=0, null=True)),
                ('today_total', models.IntegerField(default=0, null=True)),
                ('difference', models.IntegerField(default=0, null=True)),
                ('yesterday_icospeaks', models.IntegerField(default=0, null=True)),
                ('today_icospeaks', models.IntegerField(default=0, null=True)),
                ('yesterday_cryptocom', models.IntegerField(default=0, null=True)),
                ('today_cryptocom', models.IntegerField(default=0, null=True)),
                ('yesterday_coinmarket', models.IntegerField(default=0, null=True)),
                ('today_coinmarket', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
