# Generated by Django 4.0 on 2022-01-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchdata', '0003_scraperdata_delete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdata',
            name='scraper_name',
            field=models.CharField(choices=[('T', 'Telegram'), ('R', 'Reddit')], max_length=255),
        ),
    ]
