# Generated by Django 4.0 on 2022-01-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fetchdata', '0004_alter_scraperdata_scraper_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/output_files/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='documents/input_files/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('output_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='fetchdata.outputfileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='auth.user')),
            ],
        ),
    ]
