# Generated by Django 4.0 on 2022-01-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fetchdata', '0006_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='input_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_file', to='fetchdata.inputfileupload'),
        ),
    ]
